import priceSheet from "@/data/prices.json";

export type Category = "pokemon" | "baseball" | "basketball" | "onepiece";

export interface RaritySlot {
  name: string;
  odds: string;
  oddsNum: number;
  avgValue: number;
}

export interface Product {
  id: string;
  category: Category;
  name: string;
  format: string;
  defaultPrice: number;
  slots: RaritySlot[];
  notes?: string;
  accent?: string;
  emoji?: string;
  image?: string;
  tag?: "hot" | "value" | "chase";
}

export const categories: { id: Category; label: string; emoji: string; color: string }[] = [
  { id: "pokemon", label: "Pokémon", emoji: "⚡", color: "from-yellow-400 to-amber-500" },
  { id: "baseball", label: "Topps Baseball", emoji: "⚾", color: "from-red-500 to-rose-600" },
  { id: "basketball", label: "Basketball", emoji: "🏀", color: "from-orange-500 to-amber-600" },
  { id: "onepiece", label: "One Piece", emoji: "🏴‍☠️", color: "from-blue-500 to-cyan-500" },
];

const rawProducts: Product[] = [
  // ========== POKÉMON ==========
  {
    id: "poke-ascended-pack",
    category: "pokemon",
    name: "Ascended Heroes",
    format: "Booster Pack",
    defaultPrice: 13.85,
    accent: "from-violet-600 to-fuchsia-500",
    emoji: "🦸",
    tag: "hot",
    image: "/products/poke-ascended-pack.webp",
    slots: [
      { name: "Bulk (Commons + Uncommons)", odds: "~100%", oddsNum: 1.0, avgValue: 1.87 },
      { name: "Double Rare (RR)", odds: "1:5", oddsNum: 0.2, avgValue: 1.3 },
      { name: "Illustration Rare (IR)", odds: "1:9", oddsNum: 0.111, avgValue: 8.43 },
      { name: "Ultra Rare (UR)", odds: "1:21", oddsNum: 0.048, avgValue: 1.9 },
      { name: "Mega Attack Rare (MAR)", odds: "1:29", oddsNum: 0.0345, avgValue: 17.46 },
      { name: "Special Illustration Rare (SIR)", odds: "1:70", oddsNum: 0.0143, avgValue: 201.77 },
      { name: "Mega Hyper Rare (MHR)", odds: "1:540", oddsNum: 0.00185, avgValue: 305.71 },
    ],
    notes: "Chase set. Slot averages recalibrated to ThePriceDex (~Sep 3 2026) + TCGPlayer pull rates. Pack EV ~$7.21 vs ~$14 market — deep −EV; fun, not +EV.",
  },
  {
    id: "poke-ascended-etb",
    category: "pokemon",
    name: "Ascended Heroes",
    format: "Elite Trainer Box (9 packs)",
    defaultPrice: 168,
    accent: "from-violet-700 to-purple-500",
    emoji: "📦",
    image: "/products/poke-ascended-etb.webp",
    tag: "chase",
    slots: [
      { name: "Bulk value across 9 packs", odds: "guaranteed", oddsNum: 1, avgValue: 7 },
      { name: "Double Rares + IRs (expected)", odds: "several", oddsNum: 1, avgValue: 28 },
      { name: "Ultra / Mega Attack Rares", odds: "expected", oddsNum: 1, avgValue: 18 },
      { name: "SIR chance (across box)", odds: "~1:8 boxes", oddsNum: 0.13, avgValue: 201.77 },
      { name: "MHR chance", odds: "very low", oddsNum: 0.017, avgValue: 305.71 },
    ],
    notes: "ETB approximation. High variance. Promo/accessories not fully valued.",
  },
  {
    id: "poke-ascended-bundle",
    category: "pokemon",
    name: "Ascended Heroes",
    format: "Booster Bundle (6 packs)",
    defaultPrice: 84,
    accent: "from-fuchsia-700 to-violet-600",
    emoji: "📦",
    image: "/products/poke-ascended-bundle.webp",
    tag: "hot",
    slots: [
      { name: "Bulk across 6 packs", odds: "guaranteed", oddsNum: 1, avgValue: 4.8 },
      { name: "RRs + IRs expected", odds: "several", oddsNum: 1, avgValue: 18 },
      { name: "URs + MARs expected", odds: "some", oddsNum: 1, avgValue: 12 },
      { name: "SIR chance (across bundle)", odds: "~1:12", oddsNum: 0.085, avgValue: 201.77 },
      { name: "MHR chance", odds: "very low", oddsNum: 0.011, avgValue: 305.71 },
    ],
    notes: "Official EN product for this set (no traditional 36-pack box). Still often negative at secondary prices.",
  },
  {
    id: "poke-surging-pack",
    category: "pokemon",
    name: "Surging Sparks",
    format: "Booster Pack",
    defaultPrice: 7.85,
    accent: "from-yellow-500 to-orange-400",
    emoji: "⚡",
    image: "/products/poke-surging-pack.webp",
    slots: [
      { name: "Bulk", odds: "~100%", oddsNum: 1, avgValue: 0.45 },
      { name: "Rare / Holo", odds: "1:4", oddsNum: 0.25, avgValue: 1.4 },
      { name: "Double Rare / EX", odds: "1:8", oddsNum: 0.125, avgValue: 5 },
      { name: "Illustration Rare", odds: "1:12", oddsNum: 0.083, avgValue: 14 },
      { name: "SIR / Special", odds: "1:60", oddsNum: 0.017, avgValue: 95 },
    ],
    notes: "Sealed aged into mid-premium. Re-check EV at current ~$8 pack prices.",
  },
  {
    id: "poke-destined-pack",
    category: "pokemon",
    name: "Destined Rivals",
    format: "Booster Pack",
    defaultPrice: 9.0,
    accent: "from-red-600 to-orange-500",
    emoji: "🔥",
    image: "/products/poke-destined-pack.webp",
    tag: "chase",
    slots: [
      { name: "Bulk", odds: "~100%", oddsNum: 1, avgValue: 0.4 },
      { name: "Rare / Holo", odds: "1:4", oddsNum: 0.25, avgValue: 1.3 },
      { name: "EX / Double Rare", odds: "1:7", oddsNum: 0.14, avgValue: 5.5 },
      { name: "Illustration Rare", odds: "1:14", oddsNum: 0.07, avgValue: 15 },
      { name: "SIR / Chase", odds: "1:65", oddsNum: 0.015, avgValue: 110 },
    ],
    notes: "Still chase-hot (Team Rocket) but market openings are usually deep −EV near $9.",
  },
  {
    id: "poke-journey-pack",
    category: "pokemon",
    name: "Journey Together",
    format: "Booster Pack",
    defaultPrice: 6.6,
    accent: "from-emerald-500 to-teal-400",
    emoji: "🗺️",
    image: "/products/poke-journey-pack.webp",
    slots: [
      { name: "Bulk", odds: "~100%", oddsNum: 1, avgValue: 0.35 },
      { name: "Rare / Holo", odds: "1:4", oddsNum: 0.25, avgValue: 1.2 },
      { name: "EX / Double Rare", odds: "1:8", oddsNum: 0.125, avgValue: 4.5 },
      { name: "Illustration Rare", odds: "1:15", oddsNum: 0.067, avgValue: 12 },
      { name: "SIR / Special", odds: "1:70", oddsNum: 0.014, avgValue: 85 },
    ],
    notes: "Cheaper than many peers but EV writeups flag soft SIR floors — not a VALUE badge at $6.60.",
  },
  {
    id: "poke-prismatic-pack",
    category: "pokemon",
    name: "Prismatic Evolutions",
    format: "Booster Pack",
    defaultPrice: 14.8,
    accent: "from-pink-500 to-rose-400",
    emoji: "✨",
    image: "/products/poke-prismatic-pack.webp",
    tag: "hot",
    slots: [
      { name: "Bulk / Commons", odds: "~50%", oddsNum: 0.5, avgValue: 0.3 },
      { name: "Rare / Holo", odds: "1:4", oddsNum: 0.25, avgValue: 2 },
      { name: "Ultra / EX", odds: "1:10", oddsNum: 0.1, avgValue: 8 },
      { name: "Illustration Rare", odds: "1:15", oddsNum: 0.067, avgValue: 22 },
      { name: "Special Illustration Rare", odds: "1:70", oddsNum: 0.014, avgValue: 180 },
      { name: "Master Ball / Big Chase", odds: "1:600+", oddsNum: 0.0017, avgValue: 900 },
    ],
    notes: "Still a major chase set. Usually deep negative EV at secondary prices.",
  },
  {
    id: "poke-obsidian-pack",
    category: "pokemon",
    name: "Obsidian Flames",
    format: "Booster Pack",
    defaultPrice: 12.9,
    accent: "from-orange-700 to-red-500",
    emoji: "🌋",
    image: "/products/poke-obsidian-pack.webp",
    slots: [
      { name: "Bulk", odds: "~100%", oddsNum: 1, avgValue: 0.3 },
      { name: "Rare / Holo", odds: "1:4", oddsNum: 0.25, avgValue: 1.0 },
      { name: "EX / Double Rare", odds: "1:8", oddsNum: 0.125, avgValue: 4 },
      { name: "Illustration Rare", odds: "1:16", oddsNum: 0.062, avgValue: 10 },
      { name: "SIR / Special", odds: "1:75", oddsNum: 0.013, avgValue: 70 },
    ],
    notes: "Sealed scarce / aged premium. Not a bargain rip at ~$13.",
  },
  {
    id: "poke-temporal-pack",
    category: "pokemon",
    name: "Temporal Forces",
    format: "Booster Pack",
    defaultPrice: 11.0,
    accent: "from-sky-600 to-indigo-400",
    emoji: "⏳",
    image: "/products/poke-temporal-pack.webp",
    slots: [
      { name: "Bulk", odds: "~100%", oddsNum: 1, avgValue: 0.3 },
      { name: "Rare / Holo", odds: "1:4", oddsNum: 0.25, avgValue: 1.1 },
      { name: "EX / Double Rare", odds: "1:8", oddsNum: 0.125, avgValue: 4 },
      { name: "Illustration Rare", odds: "1:16", oddsNum: 0.062, avgValue: 11 },
      { name: "SIR / ACE / Special", odds: "1:72", oddsNum: 0.014, avgValue: 75 },
    ],
    notes: "Older modern sealed at premium — update price before treating as VALUE.",
  },
  {
    id: "poke-paradox-pack",
    category: "pokemon",
    name: "Paradox Rift",
    format: "Booster Pack",
    defaultPrice: 8.15,
    accent: "from-violet-600 to-blue-500",
    emoji: "🌀",
    image: "/products/poke-paradox-pack.webp",
    slots: [
      { name: "Bulk", odds: "~100%", oddsNum: 1, avgValue: 0.3 },
      { name: "Rare / Holo", odds: "1:4", oddsNum: 0.25, avgValue: 1.15 },
      { name: "EX / Double Rare", odds: "1:8", oddsNum: 0.125, avgValue: 4.2 },
      { name: "Illustration Rare", odds: "1:15", oddsNum: 0.067, avgValue: 12 },
      { name: "SIR / Special", odds: "1:70", oddsNum: 0.014, avgValue: 80 },
    ],
    notes: "Older set; pack market has moved well above the old ~$3.40 default.",
  },
  {
    id: "poke-paldea-pack",
    category: "pokemon",
    name: "Paldea Evolved",
    format: "Booster Pack",
    defaultPrice: 16.25,
    accent: "from-lime-500 to-green-500",
    emoji: "🌿",
    image: "/products/poke-paldea-pack.webp",
    slots: [
      { name: "Bulk", odds: "~100%", oddsNum: 1, avgValue: 0.28 },
      { name: "Rare / Holo", odds: "1:4", oddsNum: 0.25, avgValue: 1.0 },
      { name: "EX / Double Rare", odds: "1:8", oddsNum: 0.125, avgValue: 3.8 },
      { name: "Illustration Rare", odds: "1:18", oddsNum: 0.055, avgValue: 9 },
      { name: "SIR / Special", odds: "1:80", oddsNum: 0.0125, avgValue: 65 },
    ],
    notes: "Oldest SV on the list — sealed scarce; not VALUE at ~$16.",
  },
  {
    id: "poke-surging-bb",
    category: "pokemon",
    name: "Surging Sparks",
    format: "Booster Box (36 packs)",
    defaultPrice: 300,
    accent: "from-yellow-600 to-orange-500",
    emoji: "🗃️",
    image: "/products/poke-surging-bb.webp",
    slots: [
      { name: "Bulk across box", odds: "guaranteed", oddsNum: 1, avgValue: 16 },
      { name: "Rares / EXs expected", odds: "many", oddsNum: 1, avgValue: 45 },
      { name: "IRs expected", odds: "several", oddsNum: 1, avgValue: 35 },
      { name: "SIR chance", odds: "~0.6", oddsNum: 0.6, avgValue: 95 },
    ],
    notes: "Box market ~$290–$304 as of early Sep 2026. No longer a VALUE default.",
  },


  {
    id: "poke-chaos-rising-pack",
    category: "pokemon",
    name: "Chaos Rising",
    format: "Booster Pack",
    defaultPrice: 5.36,
    accent: "from-cyan-600 to-teal-400",
    emoji: "🌊",
    image: "/products/poke-chaos-rising-pack.webp",
    tag: "value",
    slots: [
      { name: "Bulk", odds: "~100%", oddsNum: 1, avgValue: 0.4 },
      { name: "Rare / Holo", odds: "1:4", oddsNum: 0.25, avgValue: 1.3 },
      { name: "EX / Double Rare", odds: "1:8", oddsNum: 0.125, avgValue: 5 },
      { name: "Illustration Rare", odds: "1:14", oddsNum: 0.07, avgValue: 14 },
      { name: "SIR / Special", odds: "1:65", oddsNum: 0.015, avgValue: 100 },
    ],
    notes: "Sep 2026 VALUE proxy — cheapest recent ME main-set pack print. Pull-rate values are placeholders until refreshed.",
  },
  {
    id: "poke-perfect-order-pack",
    category: "pokemon",
    name: "Perfect Order",
    format: "Booster Pack",
    defaultPrice: 5.45,
    accent: "from-stone-500 to-zinc-400",
    emoji: "🧩",
    image: "/products/poke-perfect-order-pack.webp",
    tag: "value",
    slots: [
      { name: "Bulk", odds: "~100%", oddsNum: 1, avgValue: 0.4 },
      { name: "Rare / Holo", odds: "1:4", oddsNum: 0.25, avgValue: 1.3 },
      { name: "EX / Double Rare", odds: "1:8", oddsNum: 0.125, avgValue: 5 },
      { name: "Illustration Rare", odds: "1:14", oddsNum: 0.07, avgValue: 14 },
      { name: "SIR / Special", odds: "1:65", oddsNum: 0.015, avgValue: 95 },
    ],
    notes: "Sep 2026 VALUE proxy — near-floor modern pricing. Pull-rate values are placeholders until refreshed.",
  },
  {
    id: "poke-pitch-black-pack",
    category: "pokemon",
    name: "Pitch Black",
    format: "Booster Pack",
    defaultPrice: 5.67,
    accent: "from-zinc-800 to-violet-700",
    emoji: "🌑",
    image: "/products/poke-pitch-black-pack.webp",
    tag: "value",
    slots: [
      { name: "Bulk", odds: "~100%", oddsNum: 1, avgValue: 0.4 },
      { name: "Rare / Holo", odds: "1:4", oddsNum: 0.25, avgValue: 1.35 },
      { name: "EX / Double Rare", odds: "1:8", oddsNum: 0.125, avgValue: 5.5 },
      { name: "Illustration Rare", odds: "1:14", oddsNum: 0.07, avgValue: 15 },
      { name: "SIR / Special", odds: "1:65", oddsNum: 0.015, avgValue: 110 },
    ],
    notes: "Newest English main set (Jul 2026). VALUE proxy on pack price + Darkrai chase; pull rates are placeholders.",
  },

  // ========== 30TH CELEBRATION (EN Sep 2026) ==========
  {
    id: "poke-30th-etb",
    category: "pokemon",
    name: "30th Celebration Elite Trainer Box",
    format: "Elite Trainer Box",
    defaultPrice: 165.97,
    accent: "from-yellow-400 to-amber-600",
    emoji: "🎉",
    tag: "chase",
    image: "/products/poke-30th-etb.webp",
    slots: [
      { name: "Pack hits across 9 packs (pre-release est.)", odds: "est.", oddsNum: 1, avgValue: 19.12 },
      { name: "Promo / accessories (est.)", odds: "included", oddsNum: 1, avgValue: 15 },
      { name: "Big chase upside (est.)", odds: "low", oddsNum: 0.12, avgValue: 120 },
    ],
    notes: "9 packs; full-art Nidorina promo; 16 foil energy; sleeves; dice; coin; dividers; player's guide; Live code. Pre-release EV slots are placeholders until pull rates settle. MSRP $49.99; default uses early secondary ~$165.97.",
  },
  {
    id: "poke-30th-pc-etb",
    category: "pokemon",
    name: "30th Celebration Pokémon Center Elite Trainer Box",
    format: "Pokémon Center Elite Trainer Box",
    defaultPrice: 490.64,
    accent: "from-amber-500 to-orange-400",
    emoji: "🎉",
    tag: "chase",
    image: "/products/poke-30th-pc-etb.webp",
    slots: [
      { name: "Pack hits across 11 packs (pre-release est.)", odds: "est.", oddsNum: 1, avgValue: 23.38 },
      { name: "Promo / accessories (est.)", odds: "included", oddsNum: 1, avgValue: 15 },
      { name: "Big chase upside (est.)", odds: "low", oddsNum: 0.12, avgValue: 120 },
    ],
    notes: "11 packs; two Nidorina promos (one with PC stamp); PC exclusive. Pre-release EV slots are placeholders until pull rates settle. MSRP $59.99; default uses early secondary ~$490.64.",
  },
  {
    id: "poke-30th-bundle",
    category: "pokemon",
    name: "30th Celebration Booster Bundle",
    format: "Booster Bundle",
    defaultPrice: 92.76,
    accent: "from-yellow-400 to-amber-600",
    emoji: "🎉",
    tag: "hot",
    image: "/products/poke-30th-bundle.webp",
    slots: [
      { name: "Pack hits across 6 packs (pre-release est.)", odds: "est.", oddsNum: 1, avgValue: 15.0 },
      { name: "Promo / accessories (est.)", odds: "included", oddsNum: 1, avgValue: 10 },
      { name: "Chase upside (est.)", odds: "low", oddsNum: 0.1, avgValue: 80 },
    ],
    notes: "6 packs; no promo. Best pack-density SKU after ETB for EV calc. Pre-release EV slots are placeholders until pull rates settle. MSRP $26.94; default uses early secondary ~$92.76.",
  },
  {
    id: "poke-30th-poster",
    category: "pokemon",
    name: "30th Celebration Poster Collection",
    format: "Poster Collection",
    defaultPrice: 52.99,
    accent: "from-amber-500 to-orange-400",
    emoji: "🎉",
    tag: "hot",
    image: "/products/poke-30th-poster.webp",
    slots: [
      { name: "Pack hits across 3 packs (pre-release est.)", odds: "est.", oddsNum: 1, avgValue: 7.5 },
      { name: "Promo / accessories (est.)", odds: "included", oddsNum: 1, avgValue: 10 },
      { name: "Chase upside (est.)", odds: "low", oddsNum: 0.1, avgValue: 80 },
    ],
    notes: "3 packs; Articuno / Zapdos / Moltres promos; two-sided poster. Pre-release EV slots are placeholders until pull rates settle. MSRP $14.99; default uses early secondary ~$52.99.",
  },
  {
    id: "poke-30th-tech-sticker-exeggutor",
    category: "pokemon",
    name: "30th Celebration Tech Sticker Collection — Alolan Exeggutor",
    format: "Tech Sticker Collection",
    defaultPrice: 44.32,
    accent: "from-yellow-400 to-amber-600",
    emoji: "🎉",
    tag: "hot",
    image: "/products/poke-30th-tech-sticker-exeggutor.webp",
    slots: [
      { name: "Pack hits across 3 packs (pre-release est.)", odds: "est.", oddsNum: 1, avgValue: 7.5 },
      { name: "Promo / accessories (est.)", odds: "included", oddsNum: 1, avgValue: 10 },
      { name: "Chase upside (est.)", odds: "low", oddsNum: 0.1, avgValue: 80 },
    ],
    notes: "3 packs; Alolan Exeggutor foil promo; matching sticker sheet. Pre-release EV slots are placeholders until pull rates settle. MSRP $14.99; default uses early secondary ~$44.32.",
  },
  {
    id: "poke-30th-tech-sticker-lucario",
    category: "pokemon",
    name: "30th Celebration Tech Sticker Collection — Lucario",
    format: "Tech Sticker Collection",
    defaultPrice: 38.3,
    accent: "from-amber-500 to-orange-400",
    emoji: "🎉",
    tag: "hot",
    image: "/products/poke-30th-tech-sticker-lucario.webp",
    slots: [
      { name: "Pack hits across 3 packs (pre-release est.)", odds: "est.", oddsNum: 1, avgValue: 7.5 },
      { name: "Promo / accessories (est.)", odds: "included", oddsNum: 1, avgValue: 10 },
      { name: "Chase upside (est.)", odds: "low", oddsNum: 0.1, avgValue: 80 },
    ],
    notes: "3 packs; Lucario foil promo; matching sticker sheet. Pre-release EV slots are placeholders until pull rates settle. MSRP $14.99; default uses early secondary ~$38.3.",
  },
  {
    id: "poke-30th-ex-box-sylveon",
    category: "pokemon",
    name: "30th Celebration Pokémon ex Box — Sylveon ex",
    format: "Pokémon ex Box",
    defaultPrice: 78.36,
    accent: "from-yellow-400 to-amber-600",
    emoji: "🎉",
    tag: "hot",
    image: "/products/poke-30th-ex-box-sylveon.webp",
    slots: [
      { name: "Pack hits across 4 packs (pre-release est.)", odds: "est.", oddsNum: 1, avgValue: 10.0 },
      { name: "Promo / accessories (est.)", odds: "included", oddsNum: 1, avgValue: 10 },
      { name: "Chase upside (est.)", odds: "low", oddsNum: 0.1, avgValue: 80 },
    ],
    notes: "4 packs; Sylveon ex promo + oversize card. Pre-release EV slots are placeholders until pull rates settle. MSRP $21.99; default uses early secondary ~$78.36.",
  },
  {
    id: "poke-30th-ex-box-greninja",
    category: "pokemon",
    name: "30th Celebration Pokémon ex Box — Greninja ex",
    format: "Pokémon ex Box",
    defaultPrice: 54.69,
    accent: "from-amber-500 to-orange-400",
    emoji: "🎉",
    tag: "hot",
    image: "/products/poke-30th-ex-box-greninja.webp",
    slots: [
      { name: "Pack hits across 4 packs (pre-release est.)", odds: "est.", oddsNum: 1, avgValue: 10.0 },
      { name: "Promo / accessories (est.)", odds: "included", oddsNum: 1, avgValue: 10 },
      { name: "Chase upside (est.)", odds: "low", oddsNum: 0.1, avgValue: 80 },
    ],
    notes: "4 packs; Greninja ex promo + oversize card. Pre-release EV slots are placeholders until pull rates settle. MSRP $21.99; default uses early secondary ~$54.69.",
  },
  {
    id: "poke-30th-knockout",
    category: "pokemon",
    name: "30th Celebration Knock Out Collection",
    format: "Knock Out Collection",
    defaultPrice: 27.49,
    accent: "from-yellow-400 to-amber-600",
    emoji: "🎉",
    tag: "hot",
    image: "/products/poke-30th-knockout.webp",
    slots: [
      { name: "Pack hits across 2 packs (pre-release est.)", odds: "est.", oddsNum: 1, avgValue: 5.6 },
      { name: "Promo / accessories (est.)", odds: "included", oddsNum: 1, avgValue: 8 },
      { name: "Chase upside (est.)", odds: "low", oddsNum: 0.08, avgValue: 60 },
    ],
    notes: "2 packs; Eevee foil promo; commemorative coin. Pre-release EV slots are placeholders until pull rates settle. MSRP $9.99; default uses early secondary ~$27.49.",
  },
  {
    id: "poke-30th-binder",
    category: "pokemon",
    name: "30th Celebration Binder Collection",
    format: "Binder Collection",
    defaultPrice: 81.44,
    accent: "from-amber-500 to-orange-400",
    emoji: "🎉",
    tag: "hot",
    image: "/products/poke-30th-binder.webp",
    slots: [
      { name: "Pack hits across 5 packs (pre-release est.)", odds: "est.", oddsNum: 1, avgValue: 12.5 },
      { name: "Promo / accessories (est.)", odds: "included", oddsNum: 1, avgValue: 10 },
      { name: "Chase upside (est.)", odds: "low", oddsNum: 0.1, avgValue: 80 },
    ],
    notes: "5 packs + 9-pocket portfolio. Possible delay to 2026-12-04 reported; verify on pokemon.com before launch. Pre-release EV slots are placeholders until pull rates settle. MSRP $31.99; default uses early secondary ~$81.44.",
  },
  {
    id: "poke-30th-mini-tin",
    category: "pokemon",
    name: "30th Celebration Day & Night Mini Tin",
    format: "Mini Tin",
    defaultPrice: 65.65,
    accent: "from-yellow-400 to-amber-600",
    emoji: "🎉",
    tag: "hot",
    image: "/products/poke-30th-mini-tin.webp",
    slots: [
      { name: "Pack hits across 2 packs (pre-release est.)", odds: "est.", oddsNum: 1, avgValue: 5.6 },
      { name: "Promo / accessories (est.)", odds: "included", oddsNum: 1, avgValue: 8 },
      { name: "Chase upside (est.)", odds: "low", oddsNum: 0.08, avgValue: 60 },
    ],
    notes: "2 packs + sticker sheet + art card. Multiple art variants (Day/Night Pikachu, Espeon, Umbreon, etc.). Pre-release EV slots are placeholders until pull rates settle. MSRP $9.99; default uses early secondary ~$65.65.",
  },
  {
    id: "poke-30th-upc-day",
    category: "pokemon",
    name: "30th Celebration Ultra-Premium Collection — Day",
    format: "Ultra-Premium Collection",
    defaultPrice: 620.73,
    accent: "from-amber-500 to-orange-400",
    emoji: "🎉",
    tag: "chase",
    image: "/products/poke-30th-upc-day.webp",
    slots: [
      { name: "Pack hits across 30 packs (pre-release est.)", odds: "est.", oddsNum: 1, avgValue: 63.75 },
      { name: "Promo / accessories (est.)", odds: "included", oddsNum: 1, avgValue: 15 },
      { name: "Big chase upside (est.)", odds: "low", oddsNum: 0.12, avgValue: 120 },
    ],
    notes: "29× 30th Celebration boosters + 1 Classic Collection 3-card pack; Pikachu ex (day) + Espeon ex; playmat/sleeves/deck box. Pre-release EV slots are placeholders until pull rates settle. MSRP $179.99; default uses early secondary ~$620.73.",
  },
  {
    id: "poke-30th-upc-night",
    category: "pokemon",
    name: "30th Celebration Ultra-Premium Collection — Night",
    format: "Ultra-Premium Collection",
    defaultPrice: 661.35,
    accent: "from-yellow-400 to-amber-600",
    emoji: "🎉",
    tag: "chase",
    image: "/products/poke-30th-upc-night.webp",
    slots: [
      { name: "Pack hits across 30 packs (pre-release est.)", odds: "est.", oddsNum: 1, avgValue: 63.75 },
      { name: "Promo / accessories (est.)", odds: "included", oddsNum: 1, avgValue: 15 },
      { name: "Big chase upside (est.)", odds: "low", oddsNum: 0.12, avgValue: 120 },
    ],
    notes: "29 regular packs + 1 Classic Collection pack; Pikachu ex (night) + Umbreon ex. Pre-release EV slots are placeholders until pull rates settle. MSRP $179.99; default uses early secondary ~$661.35.",
  },

  // ========== BASKETBALL ==========
  {
    id: "bball-chrome-update-value",
    category: "basketball",
    name: "2025-26 Topps Chrome Update",
    format: "Value / Blaster Box",
    defaultPrice: 55,
    accent: "from-yellow-600 to-orange-300",
    emoji: "🎴",
    image: "/products/bball-chrome-update-value.webp",
    tag: "value",
    slots: [
      { name: "Base + Refractors", odds: "solid", oddsNum: 1, avgValue: 14 },
      { name: "Parallels / Inserts", odds: "some", oddsNum: 1, avgValue: 18 },
      { name: "Numbered / Auto chance", odds: "low", oddsNum: 0.06, avgValue: 90 },
    ],
    notes: "Often better relative EV than Hobby when bought under ~$60.",
  },
  {
    id: "bball-chrome-update-mega",
    category: "basketball",
    name: "2025-26 Topps Chrome Update",
    format: "Mega Box",
    defaultPrice: 130,
    accent: "from-amber-600 to-yellow-400",
    emoji: "📦",
    image: "/products/bball-chrome-update-mega.webp",
    tag: "value",
    slots: [
      { name: "Base + Refractors / X-Fractors", odds: "strong", oddsNum: 1, avgValue: 28 },
      { name: "Numbered parallels", odds: "low", oddsNum: 1, avgValue: 25 },
      { name: "Inserts", odds: "several", oddsNum: 1, avgValue: 18 },
      { name: "Auto chance", odds: "low", oddsNum: 0.14, avgValue: 160 },
    ],
    notes: "Mega can beat Hobby on EV at the right price.",
  },
  {
    id: "bball-chrome-update-hobby",
    category: "basketball",
    name: "2025-26 Topps Chrome Update",
    format: "Hobby Box (20 packs / 1 auto)",
    defaultPrice: 950,
    accent: "from-orange-600 to-amber-400",
    emoji: "🏀",
    image: "/products/bball-chrome-update-hobby.webp",
    tag: "chase",
    slots: [
      { name: "Base + Refractors (box total)", odds: "many", oddsNum: 1, avgValue: 60 },
      { name: "Numbered parallels (/99+)", odds: "several", oddsNum: 1, avgValue: 80 },
      { name: "Inserts / SSPs", odds: "variable", oddsNum: 1, avgValue: 50 },
      { name: "Autograph (guaranteed)", odds: "1 per box", oddsNum: 1, avgValue: 180 },
      { name: "High-end / Debut Patch potential", odds: "very rare", oddsNum: 0.03, avgValue: 1200 },
    ],
    notes: "Hobby is chase. Extreme variance on top rookies. Often negative at $900+.",
  },
  {
    id: "bball-hoops-blaster",
    category: "basketball",
    name: "2025-26 NBA Hoops",
    format: "Blaster Box",
    defaultPrice: 28,
    accent: "from-red-600 to-orange-500",
    emoji: "🏀",
    image: "/products/bball-hoops-blaster.webp",
    tag: "value",
    slots: [
      { name: "Base + inserts", odds: "many", oddsNum: 1, avgValue: 10 },
      { name: "Parallels / rookies", odds: "some", oddsNum: 1, avgValue: 12 },
      { name: "Numbered / auto chance", odds: "low", oddsNum: 0.04, avgValue: 50 },
    ],
    notes: "Cheap entry product. Often closer to fair EV than Chrome hobby.",
  },
  {
    id: "bball-select-blaster",
    category: "basketball",
    name: "2025-26 Select",
    format: "Blaster Box",
    defaultPrice: 40,
    accent: "from-slate-600 to-zinc-400",
    emoji: "🎯",
    image: "/products/bball-select-blaster.webp",
    tag: "value",
    slots: [
      { name: "Base + inserts", odds: "many", oddsNum: 1, avgValue: 14 },
      { name: "Parallels / courtside", odds: "some", oddsNum: 1, avgValue: 16 },
      { name: "Numbered / auto chance", odds: "low", oddsNum: 0.05, avgValue: 70 },
    ],
    notes: "Mid-tier product — better EV profile than flagship hobby. 2025-26 Select basketball has no retail blaster yet — image is 2024-25 Select blaster stand-in. ,
  },

  // ========== BASEBALL ==========
  {
    id: "base-chrome-mega",
    category: "baseball",
    name: "2026 Topps Chrome",
    format: "Mega Box",
    defaultPrice: 75,
    accent: "from-rose-600 to-red-400",
    emoji: "📦",
    image: "/products/base-chrome-mega.webp",
    tag: "value",
    slots: [
      { name: "Base + Refractors", odds: "solid", oddsNum: 1, avgValue: 20 },
      { name: "Parallels / Inserts", odds: "some", oddsNum: 1, avgValue: 22 },
      { name: "Numbered / Auto chance", odds: "low", oddsNum: 0.09, avgValue: 100 },
    ],
    notes: "More accessible Chrome format. Better EV profile than hobby at these prices.",
  },
  {
    id: "base-chrome-hobby",
    category: "baseball",
    name: "2026 Topps Chrome",
    format: "Hobby Box (20 packs)",
    defaultPrice: 280,
    accent: "from-red-600 to-rose-400",
    emoji: "⚾",
    image: "/products/base-chrome-hobby.webp",
    tag: "chase",
    slots: [
      { name: "Base + Refractors", odds: "many", oddsNum: 1, avgValue: 50 },
      { name: "Numbered parallels", odds: "~1-2", oddsNum: 1, avgValue: 60 },
      { name: "Rookie Autograph", odds: "1 per box", oddsNum: 1, avgValue: 120 },
      { name: "Inserts / SPs", odds: "variable", oddsNum: 1, avgValue: 40 },
      { name: "High-end potential", odds: "very low", oddsNum: 0.05, avgValue: 400 },
    ],
    notes: "Classic Chrome. Autos drive value. Often near break-even in softer markets.",
  },
  {
    id: "base-update-hobby",
    category: "baseball",
    name: "2025 Topps Update",
    format: "Hobby Box",
    defaultPrice: 240,
    accent: "from-sky-600 to-blue-400",
    emoji: "🏟️",
    image: "/products/base-update-hobby.webp",
    tag: "value",
    slots: [
      { name: "Base + inserts", odds: "many", oddsNum: 1, avgValue: 45 },
      { name: "Rookie cards / SP", odds: "several", oddsNum: 1, avgValue: 55 },
      { name: "Autograph", odds: "1 per box", oddsNum: 1, avgValue: 110 },
      { name: "Big hit potential", odds: "low", oddsNum: 0.05, avgValue: 350 },
    ],
    notes: "Update sets can carry key rookies. Better EV when priced under ~$250.",
  },
  {
    id: "base-series1-blaster",
    category: "baseball",
    name: "2026 Topps Series 1",
    format: "Blaster Box",
    defaultPrice: 25,
    accent: "from-blue-600 to-sky-400",
    emoji: "⚾",
    image: "/products/base-series1-blaster.webp",
    tag: "value",
    slots: [
      { name: "Base + inserts", odds: "many", oddsNum: 1, avgValue: 9 },
      { name: "Parallels / rookies", odds: "some", oddsNum: 1, avgValue: 11 },
      { name: "Numbered / auto chance", odds: "low", oddsNum: 0.03, avgValue: 40 },
    ],
    notes: "Cheap fun product. Often one of the least negative EV formats.",
  },
  {
    id: "base-heritage-blaster",
    category: "baseball",
    name: "2025 Topps Heritage",
    format: "Blaster Box",
    defaultPrice: 30,
    accent: "from-amber-700 to-yellow-500",
    emoji: "📜",
    image: "/products/base-heritage-blaster.webp",
    tag: "value",
    slots: [
      { name: "Base + inserts", odds: "many", oddsNum: 1, avgValue: 11 },
      { name: "Parallels / SP", odds: "some", oddsNum: 1, avgValue: 12 },
      { name: "Auto / relic chance", odds: "low", oddsNum: 0.04, avgValue: 55 },
    ],
    notes: "Fun format with often reasonable secondary pricing.",
  },

  // ========== ONE PIECE ==========
  {
    id: "op-16-pack",
    category: "onepiece",
    name: "OP-16 The Time of Battle",
    format: "Booster Pack",
    defaultPrice: 4.5,
    accent: "from-cyan-600 to-blue-400",
    emoji: "🏴‍☠️",
    image: "/products/op-16-pack.webp",
    tag: "value",
    slots: [
      { name: "Common / Uncommon", odds: "~60%", oddsNum: 0.6, avgValue: 0.25 },
      { name: "Rare", odds: "1:4", oddsNum: 0.25, avgValue: 1.8 },
      { name: "Super Rare / Leader", odds: "1:12", oddsNum: 0.083, avgValue: 9 },
      { name: "Secret / Alt Art", odds: "1:40", oddsNum: 0.025, avgValue: 40 },
      { name: "Manga Rare / Chase", odds: "1:200+", oddsNum: 0.005, avgValue: 180 },
    ],
    notes: "Competitive set. Better EV when packs are under ~$5.",
  },
  {
    id: "op-16-box",
    category: "onepiece",
    name: "OP-16 The Time of Battle",
    format: "Booster Box (24 packs)",
    defaultPrice: 95,
    accent: "from-blue-700 to-cyan-500",
    emoji: "🗃️",
    image: "/products/op-16-box.webp",
    tag: "value",
    slots: [
      { name: "Bulk + Rares", odds: "guaranteed", oddsNum: 1, avgValue: 22 },
      { name: "SRs / Leaders expected", odds: "several", oddsNum: 1, avgValue: 40 },
      { name: "Secrets / Alts expected", odds: "~0.6", oddsNum: 0.6, avgValue: 40 },
      { name: "Manga Rare chance", odds: "~1:8 boxes", oddsNum: 0.12, avgValue: 180 },
    ],
    notes: "Box EV more stable than singles. Often one of the better OP formats.",
  },
  {
    id: "op-09-pack",
    category: "onepiece",
    name: "OP-09 Emperors in the New World",
    format: "Booster Pack",
    defaultPrice: 5.5,
    accent: "from-indigo-600 to-purple-400",
    emoji: "👑",
    image: "/products/op-09-pack.webp",
    tag: "chase",
    slots: [
      { name: "Common / Uncommon", odds: "~60%", oddsNum: 0.6, avgValue: 0.25 },
      { name: "Rare", odds: "1:4", oddsNum: 0.25, avgValue: 1.8 },
      { name: "Super Rare / Leader", odds: "1:12", oddsNum: 0.083, avgValue: 10 },
      { name: "Secret / Alt", odds: "1:35", oddsNum: 0.029, avgValue: 45 },
      { name: "Manga / SP chase", odds: "1:180", oddsNum: 0.0055, avgValue: 200 },
    ],
    notes: "Popular earlier set. Still demand-driven pricing.",
  },
];

export const pricesUpdated: string = priceSheet.updated;

export const products: Product[] = rawProducts.map((p) => {
  const override = (priceSheet.prices as Record<string, number | undefined>)[p.id];
  return override != null ? { ...p, defaultPrice: override } : p;
});

export function calculateEV(product: Product, price: number) {
  const totalEV = product.slots.reduce(
    (sum, slot) => sum + slot.oddsNum * slot.avgValue,
    0
  );
  const roi = price > 0 ? ((totalEV - price) / price) * 100 : 0;
  return { totalEV, roi, profit: totalEV - price };
}
